"""empty message

Revision ID: b1e898d0cceb
Revises: 2e0d8522cdf8
Create Date: 2023-10-20 16:48:57.710854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e898d0cceb'
down_revision = '2e0d8522cdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
        op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
        op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
